import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AddNewDevice(),
        ]),
      ),
    );
  }
}

class AddNewDevice extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 768,
          height: 709,
          padding: const EdgeInsets.symmetric(horizontal: 16),
          decoration: ShapeDecoration(
            color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            spacing: 10,
            children: [
              Container(
                width: double.infinity,
                height: 621.08,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 8.39,
                  children: [
                    Container(
                      width: double.infinity,
                      height: 621.08,
                      padding: const EdgeInsets.symmetric(horizontal: 68, vertical: 17),
                      decoration: ShapeDecoration(
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(17.63),
                        ),
                      ),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        spacing: 10,
                        children: [
                          Container(
                            width: 683.56,
                            height: 575.10,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 0,
                                  child: Container(
                                    width: 323.50,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      spacing: 10.19,
                                      children: [
                                        SizedBox(
                                          width: 323.50,
                                          child: Text(
                                            'Device Name',
                                            style: TextStyle(
                                              color: Colors.white /* Colors-Secondary-600 */,
                                              fontSize: 15.28,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.50,
                                            ),
                                          ),
                                        ),
                                        ConstrainedBox(
                                          constraints: BoxConstraints(minWidth: 305.67),
                                          child: Container(
                                            width: double.infinity,
                                            padding: const EdgeInsets.symmetric(horizontal: 20.38, vertical: 15.28),
                                            clipBehavior: Clip.antiAlias,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 2.55,
                                                  strokeAlign: BorderSide.strokeAlignCenter,
                                                  color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                ),
                                                borderRadius: BorderRadius.circular(8.47),
                                              ),
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                SizedBox(
                                                  width: 282.75,
                                                  child: Text(
                                                    'Enter your username',
                                                    style: TextStyle(
                                                      color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                      fontSize: 20.38,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 0,
                                  top: 104.91,
                                  child: Container(
                                    width: 683.19,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      spacing: 10.19,
                                      children: [
                                        SizedBox(
                                          width: 683.19,
                                          child: Text(
                                            'Device Type',
                                            style: TextStyle(
                                              color: Colors.white /* Colors-Secondary-600 */,
                                              fontSize: 15.28,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.50,
                                            ),
                                          ),
                                        ),
                                        ConstrainedBox(
                                          constraints: BoxConstraints(minWidth: 305.67),
                                          child: Container(
                                            width: double.infinity,
                                            padding: const EdgeInsets.symmetric(horizontal: 20.38, vertical: 15.28),
                                            clipBehavior: Clip.antiAlias,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 2.55,
                                                  strokeAlign: BorderSide.strokeAlignCenter,
                                                  color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                ),
                                                borderRadius: BorderRadius.circular(8.47),
                                              ),
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                SizedBox(
                                                  width: 642.44,
                                                  child: Text(
                                                    'Enter your username',
                                                    style: TextStyle(
                                                      color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                      fontSize: 20.38,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 360.06,
                                  top: 0,
                                  child: Container(
                                    width: 323.50,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      spacing: 10.19,
                                      children: [
                                        SizedBox(
                                          width: 323.50,
                                          child: Text(
                                            'Device ID',
                                            style: TextStyle(
                                              color: Colors.white /* Colors-Secondary-600 */,
                                              fontSize: 15.28,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.50,
                                            ),
                                          ),
                                        ),
                                        ConstrainedBox(
                                          constraints: BoxConstraints(minWidth: 305.67),
                                          child: Container(
                                            width: double.infinity,
                                            padding: const EdgeInsets.symmetric(horizontal: 20.38, vertical: 15.28),
                                            clipBehavior: Clip.antiAlias,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 2.55,
                                                  strokeAlign: BorderSide.strokeAlignCenter,
                                                  color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                ),
                                                borderRadius: BorderRadius.circular(8.47),
                                              ),
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                SizedBox(
                                                  width: 282.75,
                                                  child: Text(
                                                    'Enter your username',
                                                    style: TextStyle(
                                                      color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                      fontSize: 20.38,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 360.25,
                                  top: 247.59,
                                  child: Container(
                                    width: 323.13,
                                    height: 46.16,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 323.50,
                                            height: 50.71,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: -0.19,
                                                  top: 0,
                                                  child: Container(
                                                    width: 323.97,
                                                    height: 21.82,
                                                    child: Stack(
                                                      children: [
                                                        Positioned(
                                                          left: 0,
                                                          top: 0,
                                                          child: ConstrainedBox(
                                                            constraints: BoxConstraints(minWidth: 305.67),
                                                            child: Container(
                                                              width: 323.13,
                                                              height: 46.16,
                                                              padding: const EdgeInsets.symmetric(horizontal: 13.43, vertical: 10.07),
                                                              clipBehavior: Clip.antiAlias,
                                                              decoration: ShapeDecoration(
                                                                color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                                                shape: RoundedRectangleBorder(
                                                                  side: BorderSide(
                                                                    width: 1.68,
                                                                    strokeAlign: BorderSide.strokeAlignCenter,
                                                                    color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                                  ),
                                                                  borderRadius: BorderRadius.circular(8.47),
                                                                ),
                                                              ),
                                                              child: Row(
                                                                mainAxisSize: MainAxisSize.min,
                                                                mainAxisAlignment: MainAxisAlignment.start,
                                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                                children: [
                                                                  SizedBox(
                                                                    width: 296.27,
                                                                    child: Text(
                                                                      'e.g.  192.168.1.100',
                                                                      style: TextStyle(
                                                                        color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                                        fontSize: 15.11,
                                                                        fontFamily: 'Inter',
                                                                        fontWeight: FontWeight.w400,
                                                                        height: 1,
                                                                      ),
                                                                    ),
                                                                  ),
                                                                ],
                                                              ),
                                                            ),
                                                          ),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 0,
                                  top: 356.70,
                                  child: Container(
                                    width: 683.19,
                                    height: 124.22,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: ConstrainedBox(
                                            constraints: BoxConstraints(minWidth: 305.67),
                                            child: Container(
                                              width: 683.19,
                                              height: 124.22,
                                              padding: const EdgeInsets.symmetric(horizontal: 13.43, vertical: 10.07),
                                              clipBehavior: Clip.antiAlias,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                                shape: RoundedRectangleBorder(
                                                  side: BorderSide(
                                                    width: 1.68,
                                                    strokeAlign: BorderSide.strokeAlignCenter,
                                                    color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                  ),
                                                  borderRadius: BorderRadius.circular(8.47),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.start,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                children: [
                                                  SizedBox(
                                                    width: 662.21,
                                                    height: 98.20,
                                                    child: Text(
                                                      'Enter a brief description of the device or its purpose.',
                                                      style: TextStyle(
                                                        color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                        fontSize: 15.11,
                                                        fontFamily: 'Inter',
                                                        fontWeight: FontWeight.w400,
                                                        height: 1,
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 0,
                                  top: 521.21,
                                  child: Container(
                                    width: 355.86,
                                    height: 25.18,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 25.18,
                                            height: 25.18,
                                            child: Stack(),
                                          ),
                                        ),
                                        Positioned(
                                          left: 34.41,
                                          top: 5.04,
                                          child: Text(
                                            'Activate device upon registration',
                                            style: TextStyle(
                                              color: Colors.white /* Colors-Secondary-600 */,
                                              fontSize: 15.11,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 511.14,
                                  top: 533.80,
                                  child: Container(
                                    width: 172.06,
                                    height: 41.30,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 172.06,
                                            clipBehavior: Clip.antiAlias,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF42A5F5) /* Colors-Primary-500 */,
                                              shape: RoundedRectangleBorder(
                                                borderRadius: BorderRadius.circular(5.09),
                                              ),
                                            ),
                                            child: Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              crossAxisAlignment: CrossAxisAlignment.center,
                                              children: [
                                                Container(
                                                  padding: const EdgeInsets.symmetric(horizontal: 15.28, vertical: 7.64),
                                                  child: Row(
                                                    mainAxisSize: MainAxisSize.min,
                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                    crossAxisAlignment: CrossAxisAlignment.center,
                                                    spacing: 5.09,
                                                    children: [
                                                      Text(
                                                        'Add Device',
                                                        style: TextStyle(
                                                          color: Colors.white /* Colors-Neutral-100 */,
                                                          fontSize: 17.83,
                                                          fontFamily: 'Roboto',
                                                          fontWeight: FontWeight.w500,
                                                          height: 1.43,
                                                          letterSpacing: 0.13,
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 15.11,
                                          top: 10.91,
                                          child: Container(
                                            width: 20.14,
                                            height: 20.14,
                                            clipBehavior: Clip.antiAlias,
                                            decoration: BoxDecoration(),
                                            child: Stack(),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 360.06,
                                  top: 533.80,
                                  child: Container(
                                    width: 108.27,
                                    height: 41.13,
                                    padding: const EdgeInsets.symmetric(horizontal: 66.31, vertical: 11.75),
                                    decoration: ShapeDecoration(
                                      color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          width: 1.68,
                                          color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                        ),
                                        borderRadius: BorderRadius.circular(6.71),
                                      ),
                                    ),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      spacing: 8.39,
                                      children: [
                                        Text(
                                          'Cancel',
                                          style: TextStyle(
                                            color: Colors.white /* Colors-Secondary-600 */,
                                            fontSize: 17.83,
                                            fontFamily: 'Inter',
                                            fontWeight: FontWeight.w500,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 0,
                                  top: 320.61,
                                  child: Text(
                                    'Description (Option)',
                                    style: TextStyle(
                                      color: Colors.white /* Colors-Secondary-600 */,
                                      fontSize: 15.11,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w600,
                                      height: 1,
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 360.06,
                                  top: 218.22,
                                  child: Container(
                                    width: 63.79,
                                    height: 15.11,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 156.11,
                                            height: 15.11,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 0,
                                                  top: 0,
                                                  child: Text(
                                                    'IP Address (Optional)',
                                                    style: TextStyle(
                                                      color: Colors.white /* Colors-Secondary-600 */,
                                                      fontSize: 15.11,
                                                      fontFamily: 'Inter',
                                                      fontWeight: FontWeight.w600,
                                                      height: 1,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 0,
                                  top: 247.59,
                                  child: Container(
                                    width: 323.50,
                                    height: 50.71,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 323.50,
                                            height: 45.67,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 0,
                                                  top: 0,
                                                  child: Container(
                                                    width: 323.50,
                                                    height: 45.67,
                                                    child: Stack(
                                                      children: [
                                                        Positioned(
                                                          left: 0,
                                                          top: 0,
                                                          child: Container(
                                                            width: 323.50,
                                                            height: 45.67,
                                                            child: Stack(
                                                              children: [
                                                                Positioned(
                                                                  left: 0,
                                                                  top: 0,
                                                                  child: ConstrainedBox(
                                                                    constraints: BoxConstraints(minWidth: 305.67),
                                                                    child: Container(
                                                                      width: 323.50,
                                                                      padding: const EdgeInsets.symmetric(horizontal: 20.38, vertical: 15.28),
                                                                      clipBehavior: Clip.antiAlias,
                                                                      decoration: ShapeDecoration(
                                                                        color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                                                        shape: RoundedRectangleBorder(
                                                                          side: BorderSide(
                                                                            width: 1.68,
                                                                            strokeAlign: BorderSide.strokeAlignCenter,
                                                                            color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                                          ),
                                                                          borderRadius: BorderRadius.circular(8.47),
                                                                        ),
                                                                      ),
                                                                      child: Row(
                                                                        mainAxisSize: MainAxisSize.min,
                                                                        mainAxisAlignment: MainAxisAlignment.start,
                                                                        crossAxisAlignment: CrossAxisAlignment.center,
                                                                        children: [
                                                                          SizedBox(
                                                                            width: 282.75,
                                                                            child: Text(
                                                                              'e.g.  Kampala, Uganda',
                                                                              style: TextStyle(
                                                                                color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                                                fontSize: 15.11,
                                                                                fontFamily: 'Inter',
                                                                                fontWeight: FontWeight.w400,
                                                                                height: 1,
                                                                              ),
                                                                            ),
                                                                          ),
                                                                        ],
                                                                      ),
                                                                    ),
                                                                  ),
                                                                ),
                                                              ],
                                                            ),
                                                          ),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 0,
                                  top: 218.22,
                                  child: Container(
                                    width: 63.79,
                                    height: 15.11,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 63.79,
                                            height: 15.11,
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 0,
                                                  top: 0,
                                                  child: Container(
                                                    width: 63.79,
                                                    height: 15.11,
                                                    child: Stack(
                                                      children: [
                                                        Positioned(
                                                          left: 0,
                                                          top: 0,
                                                          child: Text(
                                                            'Location',
                                                            style: TextStyle(
                                                              color: Colors.white /* Colors-Secondary-600 */,
                                                              fontSize: 15.11,
                                                              fontFamily: 'Inter',
                                                              fontWeight: FontWeight.w600,
                                                              height: 1,
                                                            ),
                                                          ),
                                                        ),
                                                      ],
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}