import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Onboarding(),
        ]),
      ),
    );
  }
}

class Onboarding extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 1024,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            color: const Color(0xFF121212) /* Colors-Accent-600 */,
          ),
          child: Stack(
            children: [
              Positioned(
                left: 436,
                top: 316.34,
                child: Container(
                  width: 568,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 44,
                    children: [
                      Container(
                        height: 361.31,
                        padding: const EdgeInsets.symmetric(horizontal: 11.75, vertical: 23.50),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 24.89,
                          children: [
                            Container(
                              width: 395.12,
                              padding: const EdgeInsets.all(14.69),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 14.69,
                                children: [
                                
                                ],
                              ),
                            ),
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              spacing: 11.75,
                              children: [
                                SizedBox(
                                  width: 282,
                                  child: Text(
                                    'Safe Buddy',
                                    style: TextStyle(
                                      color: Colors.white /* Colors-Secondary-600 */,
                                      fontSize: 49.77,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w900,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                                SizedBox(
                                  width: 282,
                                  child: Text(
                                    'Your safety is our priority',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFFBDBDBD) /* Colors-Secondary-400 */,
                                      fontSize: 12,
                                      fontStyle: FontStyle.italic,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 568,
                        height: 121,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 60,
                              child: Container(
                                width: 568,
                                height: 2,
                                decoration: BoxDecoration(
                                  color: Colors.white.withValues(alpha: 0.50) /* Colors-Secondary-Alpha-50 */,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 1,
                                height: 120,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 60,
                                      child: Container(
                                        width: 1,
                                        height: 2,
                                        decoration: BoxDecoration(
                                          gradient: LinearGradient(
                                            begin: Alignment(1.00, 1.00),
                                            end: Alignment(0.00, 1.00),
                                            colors: [const Color(0xFF4CBEFF), const Color(0xFF377CDD), const Color(0xFF294772), const Color(0xFF191A1A)],
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 56,
                                      child: Container(
                                        width: 1,
                                        height: 10,
                                        decoration: BoxDecoration(
                                          gradient: LinearGradient(
                                            begin: Alignment(1.00, 1.00),
                                            end: Alignment(0.00, 1.00),
                                            colors: [const Color(0xFF0044DF), Colors.black.withValues(alpha: 0)],
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0,
                                      top: 60,
                                      child: Container(
                                        width: 1,
                                        height: 2,
                                        decoration: BoxDecoration(
                                          gradient: LinearGradient(
                                            begin: Alignment(1.00, 1.00),
                                            end: Alignment(0.00, 1.00),
                                            colors: [Colors.white, Colors.white.withValues(alpha: 0)],
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: -15,
                                      top: 52,
                                      child: Container(
                                        width: 16,
                                        height: 16,
                                        decoration: ShapeDecoration(
                                          gradient: LinearGradient(
                                            begin: Alignment(1.00, 1.00),
                                            end: Alignment(0.00, 1.00),
                                            colors: [const Color(0xFF0059DF), Colors.black.withValues(alpha: 0)],
                                          ),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(99),
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: -15,
                                      top: 52,
                                      child: Container(
                                        width: 16,
                                        height: 16,
                                        decoration: ShapeDecoration(
                                          color: Colors.white.withValues(alpha: 0.40),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(99),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}