import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Registering(),
        ]),
      ),
    );
  }
}

class Registering extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 1024,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            color: const Color(0xFF121212) /* Colors-Accent-600 */,
          ),
          child: Stack(
            children: [
              Positioned(
                left: 496,
                top: 97,
                child: Container(
                  width: 448,
                  height: 831,
                  padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF232323) /* Colors-Accent-400 */,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        color: const Color(0xFF424242) /* Colors-Accent-100 */,
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x00000000),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Expanded(
                        child: Container(
                          width: double.infinity,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Container(
                                width: 202,
                                height: 238,
                                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 16),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 16.94,
                                  children: [
                                    Container(
                                      width: 269.02,
                                      padding: const EdgeInsets.all(10),
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        spacing: 10,
                                        children: [
                                        
                                        ],
                                      ),
                                    ),
                                    Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      spacing: 8,
                                      children: [
                                        SizedBox(
                                          width: 182,
                                          child: Text(
                                            'Safe Buddy',
                                            style: TextStyle(
                                              color: Colors.white /* Colors-Secondary-600 */,
                                              fontSize: 32,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w900,
                                              height: 1.59,
                                            ),
                                          ),
                                        ),
                                        SizedBox(
                                          width: 182,
                                          child: Text(
                                            'Your safety is our priority',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: const Color(0xFFBDBDBD) /* Colors-Secondary-400 */,
                                              fontSize: 12,
                                              fontStyle: FontStyle.italic,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.50,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Container(
                        width: double.infinity,
                        padding: const EdgeInsets.symmetric(horizontal: 24),
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              color: const Color(0xFFBBBBBB) /* Colors-Neutral-400 */,
                            ),
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 19,
                          children: [
                            Text(
                              'Create Account',
                              textAlign: TextAlign.right,
                              style: TextStyle(
                                color: Colors.white /* Colors-Secondary-600 */,
                                fontSize: 32,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w700,
                                height: 0.88,
                              ),
                            ),
                            Container(
                              width: 262,
                              height: 2,
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(
                                    width: 2,
                                    color: const Color(0xFF42A5F5) /* Colors-Primary-500 */,
                                  ),
                                  borderRadius: BorderRadius.circular(100),
                                ),
                              ),
                            ),
                            Container(
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(
                                    color: const Color(0xFFBBBBBB) /* Colors-Neutral-400 */,
                                  ),
                                ),
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 18,
                                children: [
                                  Container(
                                    width: 336,
                                    height: 74,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                        ),
                                      ),
                                    ),
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 32,
                                          child: Container(
                                            width: 336,
                                            height: 42,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 1,
                                                  color: const Color(0xFFBBBBBB) /* Colors-Neutral-400 */,
                                                ),
                                                borderRadius: BorderRadius.circular(8),
                                              ),
                                            ),
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 16,
                                                  top: 8,
                                                  child: Text(
                                                    'Enter your username',
                                                    style: TextStyle(
                                                      color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                      fontSize: 16,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1.50,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Text(
                                            'Username',
                                            style: TextStyle(
                                              color: const Color(0xFFA4A4A4) /* Colors-Neutral-500 */,
                                              fontSize: 18,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w500,
                                              height: 1.33,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  Container(
                                    width: 336,
                                    height: 74,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                        ),
                                      ),
                                    ),
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 32,
                                          child: Container(
                                            width: 336,
                                            height: 42,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 1,
                                                  color: const Color(0xFFBBBBBB) /* Colors-Neutral-400 */,
                                                ),
                                                borderRadius: BorderRadius.circular(8),
                                              ),
                                            ),
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 16,
                                                  top: 8,
                                                  child: Text(
                                                    'Enter your email',
                                                    style: TextStyle(
                                                      color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                      fontSize: 16,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1.50,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Text(
                                            'Email',
                                            style: TextStyle(
                                              color: const Color(0xFFA4A4A4) /* Colors-Neutral-500 */,
                                              fontSize: 18,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w500,
                                              height: 1.33,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  Container(
                                    width: 336,
                                    height: 74,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                        ),
                                      ),
                                    ),
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 32,
                                          child: Container(
                                            width: 336,
                                            height: 42,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 1,
                                                  color: const Color(0xFFBBBBBB) /* Colors-Neutral-400 */,
                                                ),
                                                borderRadius: BorderRadius.circular(8),
                                              ),
                                            ),
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 16,
                                                  top: 8,
                                                  child: Text(
                                                    'Enter your password',
                                                    style: TextStyle(
                                                      color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                      fontSize: 16,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1.50,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Text(
                                            'Password',
                                            style: TextStyle(
                                              color: const Color(0xFFA4A4A4) /* Colors-Neutral-500 */,
                                              fontSize: 18,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w500,
                                              height: 1.33,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  Container(
                                    width: 336,
                                    height: 74,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                        ),
                                      ),
                                    ),
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 32,
                                          child: Container(
                                            width: 336,
                                            height: 42,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF1E1E1E) /* Colors-Accent-500 */,
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 1,
                                                  color: const Color(0xFFBBBBBB) /* Colors-Neutral-400 */,
                                                ),
                                                borderRadius: BorderRadius.circular(8),
                                              ),
                                            ),
                                            child: Stack(
                                              children: [
                                                Positioned(
                                                  left: 16,
                                                  top: 8,
                                                  child: Text(
                                                    'Confirm your password',
                                                    style: TextStyle(
                                                      color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                                      fontSize: 16,
                                                      fontFamily: 'Roboto',
                                                      fontWeight: FontWeight.w400,
                                                      height: 1.50,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: SizedBox(
                                            width: 162,
                                            child: Text(
                                              'Confirm Password',
                                              style: TextStyle(
                                                color: const Color(0xFFA4A4A4) /* Colors-Neutral-500 */,
                                                fontSize: 18,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w500,
                                                height: 1.33,
                                              ),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  Container(
                                    width: 336,
                                    height: 40,
                                    decoration: ShapeDecoration(
                                      color: const Color(0xFF42A5F5) /* Colors-Primary-500 */,
                                      shape: RoundedRectangleBorder(
                                        side: BorderSide(
                                          color: const Color(0xFFBBBBBB) /* Colors-Neutral-400 */,
                                        ),
                                        borderRadius: BorderRadius.circular(8),
                                      ),
                                    ),
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 113.30,
                                          top: 8,
                                          child: Text(
                                            'Create Account',
                                            style: TextStyle(
                                              color: Colors.white /* Colors-Neutral-100 */,
                                              fontSize: 18,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.33,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Text.rich(
                              TextSpan(
                                children: [
                                  TextSpan(
                                    text: 'Already have an account?',
                                    style: TextStyle(
                                      color: const Color(0xFF616161) /* Colors-Secondary-100 */,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.50,
                                    ),
                                  ),
                                  TextSpan(
                                    text: ' ',
                                    style: TextStyle(
                                      color: Colors.white /* Colors-Secondary-600 */,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.50,
                                    ),
                                  ),
                                  TextSpan(
                                    text: 'Login',
                                    style: TextStyle(
                                      color: const Color(0xFF42A5F5) /* Colors-Primary-500 */,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.50,
                                    ),
                                  ),
                                  TextSpan(
                                    text: ' ',
                                    style: TextStyle(
                                      color: Colors.white /* Colors-Secondary-600 */,
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.50,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}