```javascript
// flutter_bootstrap.js
// This file bootstraps a Flutter web app. It is typically auto-generated by Flutter tools.
// If you want to customize the bootstrap process, you can modify this file.

if (typeof window !== "undefined") {
  window.addEventListener("load", function () {
    // The main Dart entrypoint is usually main.dart.js
    var script = document.createElement("script");
    script.src = "main.dart.js";
    script.type = "application/javascript";
    script.defer = true;
    document.body.appendChild(script);
  });
}
```