name: safe_buddy_ver2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: 12.4.8
  provider: ^6.1.5
  google_maps_flutter: ^2.9.0
  geolocator: ^9.0.2
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
